### ISSUE TITLE
Double tooltips on icons

### ISSUE THREAD

**Issue by ghost** [aspittel/learn-code-from-us#65] opened 2018-10-25 23:55 UTC
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior
Only one tooltip should be shown.

## Current Behavior
Double tooltips, one behind the other on hover.

## Possible Solution
Since adding the title to the icons for accessibility, hovering on the icons produces a double tooltip.

## Context
Understandably we'd want the tooltip to show and be accessible. What we don't want is two of them.

## Your Environment
Latest Chrome 70 on macOS 10.14.1 beta.

I am assigning this issue to myself. Seems a relatively easy fix.

**Comment by twhite96** [comment] 2018-10-26 00:48
Going to close this. Got the database up and running and it seems this is not a bug. It looks weird however. I thought it was a double tooltip but it's probably just a drop shadow.

**Comment by aspittel** [comment] 2018-10-26 02:13
Opening back up -- I would love to remove it and wasn't totally sure where it was coming from with limited time!

**Comment by twhite96** [comment] 2018-10-26 03:09
@alispittel I'll work on this then. It is weird.

**Comment by aspittel** [comment] 2018-10-30 00:08
👍 @twhite96 or @josephwhittington do you want to PR with that tweak?

**Comment by josephwhittington** [comment] 2018-10-30 00:10
@aspittel  I already have the fix in a fork so I'll submit the PR.

**Comment by aspittel** [comment] 2018-10-30 00:11
Awesome, thanks!

**Comment by aspittel** [comment] 2018-10-31 19:01
Got some awesome solutions here! Thanks everybody!

**Closed as completed by aspittel** 2018-10-31 19:01 UTC
Labels: bug, help wanted
